# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/v1/admin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/chat/v1/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2
from proto.chat.v1 import channel_pb2 as proto_dot_chat_dot_v1_dot_channel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/chat/v1/admin.proto\x12\x13\x64istributed_chat.v1\x1a\x1aproto/chat/v1/common.proto\x1a\x1bproto/chat/v1/channel.proto\"{\n\x11\x43reateUserRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"s\n\x0cUserResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12.\n\x04user\x18\x02 \x01(\x0b\x32 .distributed_chat.v1.UserSummary\"m\n\x14SetUserStatusRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"i\n\x12SetUserRoleRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"a\n\x15\x41rchiveChannelRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x12\n\nchannel_id\x18\x02 \x01(\t\"\x84\x01\n\x1aManageChannelMemberRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0b\n\x03\x61\x64\x64\x18\x04 \x01(\x08\x32\xf1\x03\n\x0c\x41\x64minService\x12W\n\nCreateUser\x12&.distributed_chat.v1.CreateUserRequest\x1a!.distributed_chat.v1.UserResponse\x12]\n\rSetUserStatus\x12).distributed_chat.v1.SetUserStatusRequest\x1a!.distributed_chat.v1.UserResponse\x12Y\n\x0bSetUserRole\x12\'.distributed_chat.v1.SetUserRoleRequest\x1a!.distributed_chat.v1.UserResponse\x12\x62\n\x0e\x41rchiveChannel\x12*.distributed_chat.v1.ArchiveChannelRequest\x1a$.distributed_chat.v1.ChannelResponse\x12j\n\x13ManageChannelMember\x12/.distributed_chat.v1.ManageChannelMemberRequest\x1a\".distributed_chat.v1.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.v1.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=107
  _globals['_CREATEUSERREQUEST']._serialized_end=230
  _globals['_USERRESPONSE']._serialized_start=232
  _globals['_USERRESPONSE']._serialized_end=347
  _globals['_SETUSERSTATUSREQUEST']._serialized_start=349
  _globals['_SETUSERSTATUSREQUEST']._serialized_end=458
  _globals['_SETUSERROLEREQUEST']._serialized_start=460
  _globals['_SETUSERROLEREQUEST']._serialized_end=565
  _globals['_ARCHIVECHANNELREQUEST']._serialized_start=567
  _globals['_ARCHIVECHANNELREQUEST']._serialized_end=664
  _globals['_MANAGECHANNELMEMBERREQUEST']._serialized_start=667
  _globals['_MANAGECHANNELMEMBERREQUEST']._serialized_end=799
  _globals['_ADMINSERVICE']._serialized_start=802
  _globals['_ADMINSERVICE']._serialized_end=1299
# @@protoc_insertion_point(module_scope)
