# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.chat.v1 import admin_pb2 as proto_dot_chat_dot_v1_dot_admin__pb2
from proto.chat.v1 import channel_pb2 as proto_dot_chat_dot_v1_dot_channel__pb2
from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/distributed_chat.v1.AdminService/CreateUser',
                request_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.FromString,
                _registered_method=True)
        self.SetUserStatus = channel.unary_unary(
                '/distributed_chat.v1.AdminService/SetUserStatus',
                request_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.SetUserStatusRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.FromString,
                _registered_method=True)
        self.SetUserRole = channel.unary_unary(
                '/distributed_chat.v1.AdminService/SetUserRole',
                request_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.SetUserRoleRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ArchiveChannel = channel.unary_unary(
                '/distributed_chat.v1.AdminService/ArchiveChannel',
                request_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.ArchiveChannelRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelResponse.FromString,
                _registered_method=True)
        self.ManageChannelMember = channel.unary_unary(
                '/distributed_chat.v1.AdminService/ManageChannelMember',
                request_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.ManageChannelMemberRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageChannelMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.CreateUserRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.SerializeToString,
            ),
            'SetUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserStatus,
                    request_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.SetUserStatusRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.SerializeToString,
            ),
            'SetUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserRole,
                    request_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.SetUserRoleRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.SerializeToString,
            ),
            'ArchiveChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveChannel,
                    request_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.ArchiveChannelRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelResponse.SerializeToString,
            ),
            'ManageChannelMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageChannelMember,
                    request_deserializer=proto_dot_chat_dot_v1_dot_admin__pb2.ManageChannelMemberRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_chat.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_chat.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.AdminService/CreateUser',
            proto_dot_chat_dot_v1_dot_admin__pb2.CreateUserRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.AdminService/SetUserStatus',
            proto_dot_chat_dot_v1_dot_admin__pb2.SetUserStatusRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.AdminService/SetUserRole',
            proto_dot_chat_dot_v1_dot_admin__pb2.SetUserRoleRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_admin__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.AdminService/ArchiveChannel',
            proto_dot_chat_dot_v1_dot_admin__pb2.ArchiveChannelRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_channel__pb2.ChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageChannelMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.AdminService/ManageChannelMember',
            proto_dot_chat_dot_v1_dot_admin__pb2.ManageChannelMemberRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
