# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/v1/channel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/chat/v1/channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/chat/v1/channel.proto\x12\x13\x64istributed_chat.v1\x1a\x1aproto/chat/v1/common.proto\"Z\n\x14\x43reateChannelRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x0c\n\x04name\x18\x02 \x01(\t\"|\n\x0f\x43hannelResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12\x34\n\x07\x63hannel\x18\x02 \x01(\x0b\x32#.distributed_chat.v1.ChannelSummary\"r\n\x13ListChannelsRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"\x9b\x01\n\x14ListChannelsResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12\x35\n\x08\x63hannels\x18\x02 \x03(\x0b\x32#.distributed_chat.v1.ChannelSummary\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\"d\n\x18\x43hannelMembershipRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x12\n\nchannel_id\x18\x02 \x01(\t2\x9c\x03\n\x0e\x43hannelService\x12`\n\rCreateChannel\x12).distributed_chat.v1.CreateChannelRequest\x1a$.distributed_chat.v1.ChannelResponse\x12\x63\n\x0cListChannels\x12(.distributed_chat.v1.ListChannelsRequest\x1a).distributed_chat.v1.ListChannelsResponse\x12`\n\x0bJoinChannel\x12-.distributed_chat.v1.ChannelMembershipRequest\x1a\".distributed_chat.v1.EmptyResponse\x12\x61\n\x0cLeaveChannel\x12-.distributed_chat.v1.ChannelMembershipRequest\x1a\".distributed_chat.v1.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.v1.channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECHANNELREQUEST']._serialized_start=80
  _globals['_CREATECHANNELREQUEST']._serialized_end=170
  _globals['_CHANNELRESPONSE']._serialized_start=172
  _globals['_CHANNELRESPONSE']._serialized_end=296
  _globals['_LISTCHANNELSREQUEST']._serialized_start=298
  _globals['_LISTCHANNELSREQUEST']._serialized_end=412
  _globals['_LISTCHANNELSRESPONSE']._serialized_start=415
  _globals['_LISTCHANNELSRESPONSE']._serialized_end=570
  _globals['_CHANNELMEMBERSHIPREQUEST']._serialized_start=572
  _globals['_CHANNELMEMBERSHIPREQUEST']._serialized_end=672
  _globals['_CHANNELSERVICE']._serialized_start=675
  _globals['_CHANNELSERVICE']._serialized_end=1087
# @@protoc_insertion_point(module_scope)
