# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.chat.v1 import channel_pb2 as proto_dot_chat_dot_v1_dot_channel__pb2
from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/v1/channel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChannel = channel.unary_unary(
                '/distributed_chat.v1.ChannelService/CreateChannel',
                request_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.CreateChannelRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelResponse.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/distributed_chat.v1.ChannelService/ListChannels',
                request_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.ListChannelsRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.ListChannelsResponse.FromString,
                _registered_method=True)
        self.JoinChannel = channel.unary_unary(
                '/distributed_chat.v1.ChannelService/JoinChannel',
                request_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelMembershipRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.LeaveChannel = channel.unary_unary(
                '/distributed_chat.v1.ChannelService/LeaveChannel',
                request_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelMembershipRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.FromString,
                _registered_method=True)


class ChannelServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChannel,
                    request_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.CreateChannelRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.ListChannelsRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_channel__pb2.ListChannelsResponse.SerializeToString,
            ),
            'JoinChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinChannel,
                    request_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelMembershipRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.SerializeToString,
            ),
            'LeaveChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveChannel,
                    request_deserializer=proto_dot_chat_dot_v1_dot_channel__pb2.ChannelMembershipRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_chat.v1.ChannelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_chat.v1.ChannelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.ChannelService/CreateChannel',
            proto_dot_chat_dot_v1_dot_channel__pb2.CreateChannelRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_channel__pb2.ChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.ChannelService/ListChannels',
            proto_dot_chat_dot_v1_dot_channel__pb2.ListChannelsRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_channel__pb2.ListChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.ChannelService/JoinChannel',
            proto_dot_chat_dot_v1_dot_channel__pb2.ChannelMembershipRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.ChannelService/LeaveChannel',
            proto_dot_chat_dot_v1_dot_channel__pb2.ChannelMembershipRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_common__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
