# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/v1/file.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/chat/v1/file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/chat/v1/file.proto\x12\x13\x64istributed_chat.v1\x1a\x1aproto/chat/v1/common.proto\"\xdc\x01\n\x10UploadFileHeader\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x15\n\roriginal_name\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12\x1b\n\x13\x65xpected_size_bytes\x18\x06 \x01(\x03\x12 \n\x18\x65xpected_checksum_sha256\x18\x07 \x01(\t\"h\n\x11UploadFileRequest\x12\x37\n\x06header\x18\x01 \x01(\x0b\x32%.distributed_chat.v1.UploadFileHeaderH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"~\n\x12UploadFileResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12\x33\n\x04\x66ile\x18\x02 \x01(\x0b\x32%.distributed_chat.v1.FileMetadataView\"\\\n\x13\x44ownloadFileRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\"m\n\x14\x44ownloadFileResponse\x12\x39\n\x08metadata\x18\x01 \x01(\x0b\x32%.distributed_chat.v1.FileMetadataViewH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload2\xd5\x01\n\x0b\x46ileService\x12_\n\nUploadFile\x12&.distributed_chat.v1.UploadFileRequest\x1a\'.distributed_chat.v1.UploadFileResponse(\x01\x12\x65\n\x0c\x44ownloadFile\x12(.distributed_chat.v1.DownloadFileRequest\x1a).distributed_chat.v1.DownloadFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.v1.file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILEHEADER']._serialized_start=78
  _globals['_UPLOADFILEHEADER']._serialized_end=298
  _globals['_UPLOADFILEREQUEST']._serialized_start=300
  _globals['_UPLOADFILEREQUEST']._serialized_end=404
  _globals['_UPLOADFILERESPONSE']._serialized_start=406
  _globals['_UPLOADFILERESPONSE']._serialized_end=532
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=534
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=626
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=628
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=737
  _globals['_FILESERVICE']._serialized_start=740
  _globals['_FILESERVICE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
