# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/v1/health.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/chat/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/chat/v1/health.proto\x12\x13\x64istributed_chat.v1\x1a\x1aproto/chat/v1/common.proto\"[\n\x12HealthCheckRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x0f\n\x07service\x18\x02 \x01(\t\"\x9c\x01\n\x13HealthCheckResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12\x0f\n\x07serving\x18\x04 \x01(\x08\x12\x1d\n\x15\x61uth_metadata_present\x18\x05 \x01(\x08\x32k\n\rHealthService\x12Z\n\x05\x43heck\x12\'.distributed_chat.v1.HealthCheckRequest\x1a(.distributed_chat.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=79
  _globals['_HEALTHCHECKREQUEST']._serialized_end=170
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=173
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=329
  _globals['_HEALTHSERVICE']._serialized_start=331
  _globals['_HEALTHSERVICE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
