# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/v1/llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/chat/v1/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/chat/v1/llm.proto\x12\x13\x64istributed_chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/chat/v1/common.proto\"w\n\x10\x43onversationItem\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb6\x01\n\x11SmartReplyRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x14\n\x0crequester_id\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12\x41\n\x12\x61uthorized_context\x18\x04 \x03(\x0b\x32%.distributed_chat.v1.ConversationItem\"\x8f\x02\n\x0eSummaryRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x14\n\x0crequester_id\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12-\n\tfrom_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07to_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x41\n\x12\x61uthorized_context\x18\x06 \x03(\x0b\x32%.distributed_chat.v1.ConversationItem\"\xb6\x01\n\x11SuggestionRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x14\n\x0crequester_id\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12\x41\n\x12\x61uthorized_context\x18\x04 \x03(\x0b\x32%.distributed_chat.v1.ConversationItem\"R\n\x0bLLMResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t2\xa2\x02\n\nLLMService\x12Y\n\rGetSmartReply\x12&.distributed_chat.v1.SmartReplyRequest\x1a .distributed_chat.v1.LLMResponse\x12^\n\x15SummarizeConversation\x12#.distributed_chat.v1.SummaryRequest\x1a .distributed_chat.v1.LLMResponse\x12Y\n\rGetSuggestion\x12&.distributed_chat.v1.SuggestionRequest\x1a .distributed_chat.v1.LLMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.v1.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSATIONITEM']._serialized_start=109
  _globals['_CONVERSATIONITEM']._serialized_end=228
  _globals['_SMARTREPLYREQUEST']._serialized_start=231
  _globals['_SMARTREPLYREQUEST']._serialized_end=413
  _globals['_SUMMARYREQUEST']._serialized_start=416
  _globals['_SUMMARYREQUEST']._serialized_end=687
  _globals['_SUGGESTIONREQUEST']._serialized_start=690
  _globals['_SUGGESTIONREQUEST']._serialized_end=872
  _globals['_LLMRESPONSE']._serialized_start=874
  _globals['_LLMRESPONSE']._serialized_end=956
  _globals['_LLMSERVICE']._serialized_start=959
  _globals['_LLMSERVICE']._serialized_end=1249
# @@protoc_insertion_point(module_scope)
