# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.chat.v1 import llm_pb2 as proto_dot_chat_dot_v1_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/v1/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSmartReply = channel.unary_unary(
                '/distributed_chat.v1.LLMService/GetSmartReply',
                request_serializer=proto_dot_chat_dot_v1_dot_llm__pb2.SmartReplyRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.FromString,
                _registered_method=True)
        self.SummarizeConversation = channel.unary_unary(
                '/distributed_chat.v1.LLMService/SummarizeConversation',
                request_serializer=proto_dot_chat_dot_v1_dot_llm__pb2.SummaryRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.FromString,
                _registered_method=True)
        self.GetSuggestion = channel.unary_unary(
                '/distributed_chat.v1.LLMService/GetSuggestion',
                request_serializer=proto_dot_chat_dot_v1_dot_llm__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSmartReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSmartReply': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSmartReply,
                    request_deserializer=proto_dot_chat_dot_v1_dot_llm__pb2.SmartReplyRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.SerializeToString,
            ),
            'SummarizeConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeConversation,
                    request_deserializer=proto_dot_chat_dot_v1_dot_llm__pb2.SummaryRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.SerializeToString,
            ),
            'GetSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuggestion,
                    request_deserializer=proto_dot_chat_dot_v1_dot_llm__pb2.SuggestionRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_chat.v1.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_chat.v1.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSmartReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.LLMService/GetSmartReply',
            proto_dot_chat_dot_v1_dot_llm__pb2.SmartReplyRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.LLMService/SummarizeConversation',
            proto_dot_chat_dot_v1_dot_llm__pb2.SummaryRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.LLMService/GetSuggestion',
            proto_dot_chat_dot_v1_dot_llm__pb2.SuggestionRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_llm__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
