# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.chat.v1 import presence_pb2 as proto_dot_chat_dot_v1_dot_presence__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/v1/presence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/distributed_chat.v1.PresenceService/Heartbeat',
                request_serializer=proto_dot_chat_dot_v1_dot_presence__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_presence__pb2.PresenceResponse.FromString,
                _registered_method=True)
        self.GetPresence = channel.unary_unary(
                '/distributed_chat.v1.PresenceService/GetPresence',
                request_serializer=proto_dot_chat_dot_v1_dot_presence__pb2.GetPresenceRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_presence__pb2.PresenceResponse.FromString,
                _registered_method=True)
        self.SubscribePresence = channel.unary_stream(
                '/distributed_chat.v1.PresenceService/SubscribePresence',
                request_serializer=proto_dot_chat_dot_v1_dot_presence__pb2.SubscribePresenceRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_v1_dot_presence__pb2.PresenceEvent.FromString,
                _registered_method=True)


class PresenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePresence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_chat_dot_v1_dot_presence__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_presence__pb2.PresenceResponse.SerializeToString,
            ),
            'GetPresence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresence,
                    request_deserializer=proto_dot_chat_dot_v1_dot_presence__pb2.GetPresenceRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_presence__pb2.PresenceResponse.SerializeToString,
            ),
            'SubscribePresence': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePresence,
                    request_deserializer=proto_dot_chat_dot_v1_dot_presence__pb2.SubscribePresenceRequest.FromString,
                    response_serializer=proto_dot_chat_dot_v1_dot_presence__pb2.PresenceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_chat.v1.PresenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_chat.v1.PresenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.PresenceService/Heartbeat',
            proto_dot_chat_dot_v1_dot_presence__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_presence__pb2.PresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_chat.v1.PresenceService/GetPresence',
            proto_dot_chat_dot_v1_dot_presence__pb2.GetPresenceRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_presence__pb2.PresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distributed_chat.v1.PresenceService/SubscribePresence',
            proto_dot_chat_dot_v1_dot_presence__pb2.SubscribePresenceRequest.SerializeToString,
            proto_dot_chat_dot_v1_dot_presence__pb2.PresenceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
