# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/v1/presence.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/chat/v1/presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto.chat.v1 import common_pb2 as proto_dot_chat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/chat/v1/presence.proto\x12\x13\x64istributed_chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/chat/v1/common.proto\"H\n\x10HeartbeatRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\"[\n\x12GetPresenceRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x9c\x01\n\x10PresenceResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.ResponseStatus\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08presence\x18\x03 \x01(\t\x12\x30\n\x0clast_seen_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"b\n\x18SubscribePresenceRequest\x12\x34\n\x07\x63ontext\x18\x01 \x01(\x0b\x32#.distributed_chat.v1.RequestContext\x12\x10\n\x08user_ids\x18\x02 \x03(\t\"u\n\rPresenceEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08presence\x18\x03 \x01(\t\x12/\n\x0boccurred_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb5\x02\n\x0fPresenceService\x12Y\n\tHeartbeat\x12%.distributed_chat.v1.HeartbeatRequest\x1a%.distributed_chat.v1.PresenceResponse\x12]\n\x0bGetPresence\x12\'.distributed_chat.v1.GetPresenceRequest\x1a%.distributed_chat.v1.PresenceResponse\x12h\n\x11SubscribePresence\x12-.distributed_chat.v1.SubscribePresenceRequest\x1a\".distributed_chat.v1.PresenceEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.v1.presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=114
  _globals['_HEARTBEATREQUEST']._serialized_end=186
  _globals['_GETPRESENCEREQUEST']._serialized_start=188
  _globals['_GETPRESENCEREQUEST']._serialized_end=279
  _globals['_PRESENCERESPONSE']._serialized_start=282
  _globals['_PRESENCERESPONSE']._serialized_end=438
  _globals['_SUBSCRIBEPRESENCEREQUEST']._serialized_start=440
  _globals['_SUBSCRIBEPRESENCEREQUEST']._serialized_end=538
  _globals['_PRESENCEEVENT']._serialized_start=540
  _globals['_PRESENCEEVENT']._serialized_end=657
  _globals['_PRESENCESERVICE']._serialized_start=660
  _globals['_PRESENCESERVICE']._serialized_end=969
# @@protoc_insertion_point(module_scope)
