"""Typed inference-only gRPC service for Node 1."""

from __future__ import annotations

from datetime import UTC

import grpc

from llm_server.adapters import AdapterError, ConversationTurn, LLMTask, ModelAdapter
from proto.chat.v1 import common_pb2, llm_pb2, llm_pb2_grpc
from server.validation import abort_invalid, require_request_id, require_text


class LLMService(llm_pb2_grpc.LLMServiceServicer):
    def __init__(self, adapter: ModelAdapter, *, max_context_messages: int,
                 max_context_chars: int) -> None:
        self._adapter = adapter
        self._max_messages = max_context_messages
        self._max_chars = max_context_chars

    @staticmethod
    def _status(request_id: str) -> common_pb2.ResponseStatus:
        return common_pb2.ResponseStatus(
            code=common_pb2.STATUS_CODE_OK,
            message="generated by local model",
            request_id=request_id,
        )

    def _context(self, items, request_id: str, context: grpc.ServicerContext) -> tuple[ConversationTurn, ...]:
        if len(items) > self._max_messages:
            abort_invalid(context, request_id, "authorized context exceeds message limit")
        if sum(len(item.body) for item in items) > self._max_chars:
            abort_invalid(context, request_id, "authorized context exceeds character limit")
        turns: list[ConversationTurn] = []
        for item in items:
            require_text(item.message_id, "context.message_id", request_id, context)
            require_text(item.sender_id, "context.sender_id", request_id, context)
            require_text(item.body, "context.body", request_id, context)
            if not item.HasField("created_at"):
                abort_invalid(context, request_id, "context.created_at is required")
            created_at = item.created_at.ToDatetime(tzinfo=UTC)
            turns.append(ConversationTurn(item.message_id, item.sender_id, item.body, created_at))
        return tuple(turns)

    def _generate(self, task: LLMTask, items, request_id: str,
                  context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        turns = self._context(items, request_id, context)
        try:
            answer = self._adapter.generate(task, turns)
        except AdapterError as exc:
            context.set_trailing_metadata((("x-request-id", request_id),))
            context.abort(grpc.StatusCode.UNAVAILABLE, str(exc))
        return llm_pb2.LLMResponse(status=self._status(request_id), answer=answer)

    def GetSmartReply(self, request: llm_pb2.SmartReplyRequest,
                      context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.requester_id, "requester_id", request_id, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        return self._generate(LLMTask.SMART_REPLY, request.authorized_context, request_id, context)

    def SummarizeConversation(self, request: llm_pb2.SummaryRequest,
                              context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.requester_id, "requester_id", request_id, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        if not request.HasField("from_time") or not request.HasField("to_time"):
            abort_invalid(context, request_id, "from_time and to_time are required")
        if request.from_time.ToDatetime(tzinfo=UTC) >= request.to_time.ToDatetime(tzinfo=UTC):
            abort_invalid(context, request_id, "from_time must be before to_time")
        return self._generate(LLMTask.SUMMARY, request.authorized_context, request_id, context)

    def GetSuggestion(self, request: llm_pb2.SuggestionRequest,
                      context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.requester_id, "requester_id", request_id, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        return self._generate(LLMTask.SUGGESTION, request.authorized_context, request_id, context)
