"""Typed chat-side gRPC services through Phase 4."""

from __future__ import annotations

from collections.abc import Iterator
from datetime import UTC

import grpc
from google.protobuf.timestamp_pb2 import Timestamp

from common.errors import ApplicationError
from common.grpc_metadata import get_auth_token, get_request_id
from common.metadata import new_request_id, utc_now
from domain.models import Channel, FileMetadata, Message, Presence, User
from proto.chat.v1 import (
    admin_pb2,
    admin_pb2_grpc,
    auth_pb2,
    auth_pb2_grpc,
    channel_pb2,
    channel_pb2_grpc,
    chat_pb2,
    chat_pb2_grpc,
    common_pb2,
    file_pb2,
    file_pb2_grpc,
    health_pb2,
    health_pb2_grpc,
    llm_pb2,
    llm_pb2_grpc,
    presence_pb2,
    presence_pb2_grpc,
)
from server.application.admin import AdminApplication
from server.application.assistant import AssistantApplication, AssistantResult
from server.application.auth import AuthApplication
from server.application.channels import ChannelApplication
from server.application.chat import ChatApplication
from server.application.files import FileApplication
from server.application.presence import PresenceApplication
from server.events import EventBroker
from server.validation import (
    abort_application_error,
    abort_invalid,
    require_request_id,
    require_text,
)


def _timestamp_now() -> Timestamp:
    timestamp = Timestamp()
    timestamp.FromDatetime(utc_now())
    return timestamp


def _timestamp(value: object) -> Timestamp:
    timestamp = Timestamp()
    timestamp.FromDatetime(value)
    return timestamp


def _ok_status(request_id: str, message: str = "ok") -> common_pb2.ResponseStatus:
    return common_pb2.ResponseStatus(
        code=common_pb2.STATUS_CODE_OK,
        message=message,
        request_id=request_id,
    )


def _user_summary(user: User) -> common_pb2.UserSummary:
    return common_pb2.UserSummary(
        user_id=user.id,
        username=user.username,
        role=user.role.value,
        status=user.status.value,
    )


def _channel_summary(channel: Channel) -> common_pb2.ChannelSummary:
    return common_pb2.ChannelSummary(
        channel_id=channel.id,
        name=channel.name,
        archived=channel.is_archived,
    )


def _message_view(message: Message) -> common_pb2.MessageView:
    return common_pb2.MessageView(
        message_id=message.id,
        channel_id=message.channel_id,
        sender_id=message.sender_id,
        body=message.body,
        created_at=_timestamp(message.created_at),
        client_request_id=message.client_request_id,
    )


def _file_view(metadata: FileMetadata) -> common_pb2.FileMetadataView:
    return common_pb2.FileMetadataView(
        file_id=metadata.id,
        channel_id=metadata.channel_id,
        message_id=metadata.message_id or "",
        original_name=metadata.original_name,
        content_type=metadata.content_type,
        size_bytes=metadata.size_bytes,
        checksum_sha256=metadata.checksum_sha256,
        created_at=_timestamp(metadata.created_at),
    )


def _presence_response(presence: Presence, request_id: str) -> presence_pb2.PresenceResponse:
    return presence_pb2.PresenceResponse(
        status=_ok_status(request_id),
        user_id=presence.user_id,
        presence=presence.status.value,
        last_seen_at=_timestamp(presence.last_seen_at),
    )


def _assistant_response(result: AssistantResult, request_id: str) -> llm_pb2.LLMResponse:
    return llm_pb2.LLMResponse(
        status=common_pb2.ResponseStatus(
            code=common_pb2.STATUS_CODE_OK,
            message=(
                "generated by local LLM"
                if result.model_available
                else "local LLM unavailable; graceful fallback returned"
            ),
            request_id=request_id,
        ),
        answer=result.answer,
    )


class HealthService(health_pb2_grpc.HealthServiceServicer):
    def __init__(self, *, service_name: str, node_id: str) -> None:
        self._service_name = service_name
        self._node_id = node_id

    def Check(
        self, request: health_pb2.HealthCheckRequest, context: grpc.ServicerContext
    ) -> health_pb2.HealthCheckResponse:
        request_id = require_request_id(request.context, context)
        context.set_trailing_metadata((("x-request-id", request_id),))
        return health_pb2.HealthCheckResponse(
            status=common_pb2.ResponseStatus(
                code=common_pb2.STATUS_CODE_OK,
                message="serving",
                request_id=request_id,
            ),
            service=self._service_name,
            node_id=self._node_id,
            serving=True,
            auth_metadata_present=get_auth_token() is not None,
        )


class AuthService(auth_pb2_grpc.AuthServiceServicer):
    def __init__(self, application: AuthApplication) -> None:
        self._application = application

    def Login(
        self, request: auth_pb2.LoginRequest, context: grpc.ServicerContext
    ) -> auth_pb2.LoginResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.username, "username", request_id, context)
        require_text(request.password, "password", request_id, context)
        try:
            result = self._application.login(
                request.username, request.password, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return auth_pb2.LoginResponse(
            status=_ok_status(request_id, "login successful"),
            token=result.token,
            expires_at=_timestamp(result.expires_at),
        )

    def Logout(
        self, request: auth_pb2.LogoutRequest, context: grpc.ServicerContext
    ) -> common_pb2.EmptyResponse:
        request_id = require_request_id(request.context, context)
        try:
            self._application.logout(get_auth_token(), request_id=request_id)
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return common_pb2.EmptyResponse(status=_ok_status(request_id, "logout successful"))


class ChannelService(channel_pb2_grpc.ChannelServiceServicer):
    def __init__(self, application: ChannelApplication) -> None:
        self._application = application

    def CreateChannel(
        self, request: channel_pb2.CreateChannelRequest, context: grpc.ServicerContext
    ) -> channel_pb2.ChannelResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.name, "name", request_id, context)
        try:
            channel = self._application.create_channel(
                get_auth_token(), request.name, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return channel_pb2.ChannelResponse(
            status=_ok_status(request_id, "channel created"),
            channel=_channel_summary(channel),
        )

    def ListChannels(
        self, request: channel_pb2.ListChannelsRequest, context: grpc.ServicerContext
    ) -> channel_pb2.ListChannelsResponse:
        request_id = require_request_id(request.context, context)
        if request.page_size < 0:
            abort_invalid(context, request_id, "page_size must not be negative")
        try:
            page = self._application.list_channels(
                get_auth_token(),
                request.page_size,
                request.page_token,
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return channel_pb2.ListChannelsResponse(
            status=_ok_status(request_id),
            channels=[_channel_summary(channel) for channel in page.channels],
            next_page_token=page.next_page_token,
        )

    def JoinChannel(
        self, request: channel_pb2.ChannelMembershipRequest, context: grpc.ServicerContext
    ) -> common_pb2.EmptyResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        try:
            self._application.join_channel(
                get_auth_token(), request.channel_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return common_pb2.EmptyResponse(status=_ok_status(request_id, "channel joined"))

    def LeaveChannel(
        self, request: channel_pb2.ChannelMembershipRequest, context: grpc.ServicerContext
    ) -> common_pb2.EmptyResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        try:
            self._application.leave_channel(
                get_auth_token(), request.channel_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return common_pb2.EmptyResponse(status=_ok_status(request_id, "channel left"))


class ChatService(chat_pb2_grpc.ChatServiceServicer):
    def __init__(self, application: ChatApplication, events: EventBroker,
                 *, keepalive_seconds: float) -> None:
        self._application = application
        self._events = events
        self._keepalive_seconds = keepalive_seconds

    def SendMessage(
        self, request: chat_pb2.SendMessageRequest, context: grpc.ServicerContext
    ) -> chat_pb2.SendMessageResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.context.client_request_id, "context.client_request_id", request_id, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        require_text(request.body, "body", request_id, context)
        try:
            message = self._application.send_message(
                get_auth_token(), request.channel_id, request.body,
                request.context.client_request_id, request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return chat_pb2.SendMessageResponse(
            status=_ok_status(request_id, "message accepted"),
            message=_message_view(message),
        )

    def GetHistory(
        self, request: chat_pb2.GetHistoryRequest, context: grpc.ServicerContext
    ) -> chat_pb2.GetHistoryResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        if request.page_size < 0:
            abort_invalid(context, request_id, "page_size must not be negative")
        try:
            page = self._application.get_history(
                get_auth_token(), request.channel_id, request.page_size,
                request.page_token, request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return chat_pb2.GetHistoryResponse(
            status=_ok_status(request_id),
            messages=[_message_view(message) for message in page.messages],
            next_page_token=page.next_page_token,
        )

    def SubscribeEvents(
        self, request: chat_pb2.SubscribeEventsRequest, context: grpc.ServicerContext
    ) -> Iterator[chat_pb2.ChatEvent]:
        request_id = require_request_id(request.context, context)
        if any(not channel_id.strip() for channel_id in request.channel_ids):
            abort_invalid(context, request_id, "channel_ids must not contain empty values")
        try:
            channel_ids = self._application.authorize_subscription(
                get_auth_token(), list(request.channel_ids), request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)

        context.set_trailing_metadata((("x-request-id", request_id),))
        subscription = self._events.subscribe()
        try:
            while context.is_active():
                event = subscription.get(self._keepalive_seconds)
                if event is None:
                    yield chat_pb2.ChatEvent(
                        event_id=new_request_id(),
                        type=chat_pb2.CHAT_EVENT_TYPE_KEEPALIVE,
                        occurred_at=_timestamp_now(),
                        request_id=get_request_id() or request_id,
                    )
                elif event.kind == "message" and isinstance(event.payload, Message):
                    if event.payload.channel_id in channel_ids:
                        yield chat_pb2.ChatEvent(
                            event_id=event.id,
                            type=chat_pb2.CHAT_EVENT_TYPE_MESSAGE,
                            occurred_at=_timestamp(event.occurred_at),
                            request_id=request_id,
                            message=_message_view(event.payload),
                        )
        finally:
            subscription.close()


class PresenceService(presence_pb2_grpc.PresenceServiceServicer):
    def __init__(self, application: PresenceApplication, events: EventBroker) -> None:
        self._application = application
        self._events = events

    def Heartbeat(
        self, request: presence_pb2.HeartbeatRequest, context: grpc.ServicerContext
    ) -> presence_pb2.PresenceResponse:
        request_id = require_request_id(request.context, context)
        try:
            presence = self._application.heartbeat(get_auth_token(), request_id=request_id)
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return _presence_response(presence, request_id)

    def GetPresence(
        self, request: presence_pb2.GetPresenceRequest, context: grpc.ServicerContext
    ) -> presence_pb2.PresenceResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.user_id, "user_id", request_id, context)
        try:
            presence = self._application.get(
                get_auth_token(), request.user_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return _presence_response(presence, request_id)

    def SubscribePresence(
        self,
        request: presence_pb2.SubscribePresenceRequest,
        context: grpc.ServicerContext,
    ) -> Iterator[presence_pb2.PresenceEvent]:
        request_id = require_request_id(request.context, context)
        try:
            self._application.authenticate_subscription(
                get_auth_token(), request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        selected = set(request.user_ids)
        subscription = self._events.subscribe()
        try:
            while context.is_active():
                self._application.expire()
                event = subscription.get(0.05)
                if (
                    event is not None
                    and event.kind == "presence"
                    and isinstance(event.payload, Presence)
                    and (not selected or event.payload.user_id in selected)
                ):
                    yield presence_pb2.PresenceEvent(
                        event_id=event.id,
                        user_id=event.payload.user_id,
                        presence=event.payload.status.value,
                        occurred_at=_timestamp(event.occurred_at),
                    )
        finally:
            subscription.close()


class FileService(file_pb2_grpc.FileServiceServicer):
    def __init__(self, application: FileApplication, *, chunk_size: int) -> None:
        self._application = application
        self._chunk_size = chunk_size

    def UploadFile(
        self,
        request_iterator: Iterator[file_pb2.UploadFileRequest],
        context: grpc.ServicerContext,
    ) -> file_pb2.UploadFileResponse:
        first_request = next(request_iterator, None)
        if first_request is None or not first_request.HasField("header"):
            abort_invalid(context, get_request_id(), "first upload item must contain a header")
        request_id = require_request_id(first_request.header.context, context)
        require_text(first_request.header.channel_id, "channel_id", request_id, context)
        require_text(first_request.header.original_name, "original_name", request_id, context)

        def chunks() -> Iterator[bytes]:
            for item in request_iterator:
                if not item.HasField("chunk"):
                    abort_invalid(context, request_id, "upload items after header must be chunks")
                yield item.chunk

        try:
            metadata = self._application.upload(
                get_auth_token(),
                channel_id=first_request.header.channel_id,
                message_id=first_request.header.message_id,
                original_name=first_request.header.original_name,
                content_type=first_request.header.content_type,
                expected_size=first_request.header.expected_size_bytes,
                expected_checksum=first_request.header.expected_checksum_sha256,
                client_request_id=first_request.header.context.client_request_id,
                chunks=chunks(),
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return file_pb2.UploadFileResponse(
            status=_ok_status(request_id, "file uploaded"), file=_file_view(metadata)
        )

    def DownloadFile(
        self, request: file_pb2.DownloadFileRequest, context: grpc.ServicerContext
    ) -> Iterator[file_pb2.DownloadFileResponse]:
        request_id = require_request_id(request.context, context)
        require_text(request.file_id, "file_id", request_id, context)
        try:
            metadata, path = self._application.authorize_download(
                get_auth_token(), request.file_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        yield file_pb2.DownloadFileResponse(metadata=_file_view(metadata))
        with path.open("rb") as source:
            while context.is_active():
                chunk = source.read(self._chunk_size)
                if not chunk:
                    break
                yield file_pb2.DownloadFileResponse(chunk=chunk)


class AssistantGatewayService(llm_pb2_grpc.LLMServiceServicer):
    """Authenticated gateway that constructs context before calling Node 1."""

    def __init__(self, application: AssistantApplication) -> None:
        self._application = application

    def GetSmartReply(self, request: llm_pb2.SmartReplyRequest,
                      context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        try:
            result = self._application.smart_reply(
                get_auth_token(), request.channel_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return _assistant_response(result, request_id)

    def SummarizeConversation(self, request: llm_pb2.SummaryRequest,
                              context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        if not request.HasField("from_time") or not request.HasField("to_time"):
            abort_invalid(context, request_id, "from_time and to_time are required")
        try:
            result = self._application.summarize(
                get_auth_token(),
                request.channel_id,
                request.from_time.ToDatetime(tzinfo=UTC),
                request.to_time.ToDatetime(tzinfo=UTC),
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return _assistant_response(result, request_id)

    def GetSuggestion(self, request: llm_pb2.SuggestionRequest,
                      context: grpc.ServicerContext) -> llm_pb2.LLMResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        try:
            result = self._application.suggestion(
                get_auth_token(), request.channel_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return _assistant_response(result, request_id)


class AdminService(admin_pb2_grpc.AdminServiceServicer):
    def __init__(self, application: AdminApplication) -> None:
        self._application = application

    def CreateUser(
        self, request: admin_pb2.CreateUserRequest, context: grpc.ServicerContext
    ) -> admin_pb2.UserResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.username, "username", request_id, context)
        require_text(request.password, "password", request_id, context)
        require_text(request.role, "role", request_id, context)
        try:
            user = self._application.create_user(
                get_auth_token(),
                request.username,
                request.password,
                request.role,
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return admin_pb2.UserResponse(
            status=_ok_status(request_id, "user created"), user=_user_summary(user)
        )

    def SetUserStatus(
        self, request: admin_pb2.SetUserStatusRequest, context: grpc.ServicerContext
    ) -> admin_pb2.UserResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.user_id, "user_id", request_id, context)
        require_text(request.status, "status", request_id, context)
        try:
            user = self._application.set_user_status(
                get_auth_token(),
                request.user_id,
                request.status,
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return admin_pb2.UserResponse(
            status=_ok_status(request_id, "user status updated"),
            user=_user_summary(user),
        )

    def SetUserRole(
        self, request: admin_pb2.SetUserRoleRequest, context: grpc.ServicerContext
    ) -> admin_pb2.UserResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.user_id, "user_id", request_id, context)
        require_text(request.role, "role", request_id, context)
        try:
            user = self._application.set_user_role(
                get_auth_token(),
                request.user_id,
                request.role,
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return admin_pb2.UserResponse(
            status=_ok_status(request_id, "user role updated"),
            user=_user_summary(user),
        )

    def ArchiveChannel(
        self, request: admin_pb2.ArchiveChannelRequest, context: grpc.ServicerContext
    ) -> channel_pb2.ChannelResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        try:
            channel = self._application.archive_channel(
                get_auth_token(), request.channel_id, request_id=request_id
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return channel_pb2.ChannelResponse(
            status=_ok_status(request_id, "channel archived"),
            channel=_channel_summary(channel),
        )

    def ManageChannelMember(
        self,
        request: admin_pb2.ManageChannelMemberRequest,
        context: grpc.ServicerContext,
    ) -> common_pb2.EmptyResponse:
        request_id = require_request_id(request.context, context)
        require_text(request.channel_id, "channel_id", request_id, context)
        require_text(request.user_id, "user_id", request_id, context)
        try:
            self._application.manage_member(
                get_auth_token(),
                request.channel_id,
                request.user_id,
                request.add,
                request_id=request_id,
            )
        except ApplicationError as error:
            abort_application_error(context, error, request_id)
        return common_pb2.EmptyResponse(
            status=_ok_status(request_id, "channel membership updated")
        )
